### ISSUE TITLE
"send to" buttons disappeared

### ISSUE THREAD

**Issue by ChrisFab16** [yfszzx/stable-diffusion-webui-images-browser#24]
I've been using the embedded image browser but switched to using the extension. Now the "send to txt2img" "send to img2img" and "send to inpaint" are no longer there. when I click an image from the list, I only have the "collect" button available.

Running [737eb28](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/737eb28faca8be2bb996ee0930ec77d1f7ebd939)

![image](https://user-images.githubusercontent.com/20229082/198703178-428a96a4-49a0-403f-879c-eedddf828efa.png)

**Comment by yfszzx** [comment]
In order to add the function of sending pictures, I modified the way of webui calling “send to” function. However, the webui has not merged a new PR for several days. After webui accepts my PR, send to buttons will appear on its own.

https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/3768
